version: '3.8'

services:
  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Innoscripta
      APP_ENV: local
      APP_KEY: base64:WKaDO78IuJnT7SK7EV6W+njiqPNl3wfnwnvm1BOvAi8=
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      APP_MAINTENANCE_DRIVER: file
      PHP_CLI_SERVER_WORKERS: 4
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: Innoscripta
      DB_USERNAME: root
      DB_PASSWORD: root
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: 'false'
      SESSION_PATH: /
      SESSION_DOMAIN: null
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      MEMCACHED_HOST: 127.0.0.1
      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_MAILER: smtp
      MAIL_SCHEME: null
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: bcce57c4947bdb
      MAIL_PASSWORD: 3ca8b2ea1e2178
      MAIL_FROM_ADDRESS: hello@innoscriptag.com
      MAIL_FROM_NAME: ${APP_NAME}
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ''
      AWS_USE_PATH_STYLE_ENDPOINT: 'false'
      VITE_APP_NAME: ${APP_NAME}
      NEWS_API_KEY: 31885c63bb46444d916ef6cdccb5ffb5
      GUARDIAN_API_KEY: 19890bef-daab-48e6-9be9-3664a8cad62e
      NY_TIME_API_KEY: lNeAiovtbMJqoV67144DR2URFEuhLxJD
      NY_TIME_SECRET: YuIdUVVzNtGKYy69
    networks:
      - laravel

  # Web Server Service
  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  # Database Service
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Innoscripta
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Scheduler Service
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_scheduler
    container_name: laravel_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    command: >
      sh -c "while [ true ]; do
        php artisan schedule:run --verbose --no-interaction;
        sleep 60;
      done"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Innoscripta
      APP_ENV: local
      APP_KEY: base64:WKaDO78IuJnT7SK7EV6W+njiqPNl3wfnwnvm1BOvAi8=
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      APP_MAINTENANCE_DRIVER: file
      PHP_CLI_SERVER_WORKERS: 4
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: Innoscripta
      DB_USERNAME: root
      DB_PASSWORD: root
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: 'false'
      SESSION_PATH: /
      SESSION_DOMAIN: null
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      MEMCACHED_HOST: 127.0.0.1
      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_MAILER: smtp
      MAIL_SCHEME: null
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: bcce57c4947bdb
      MAIL_PASSWORD: 3ca8b2ea1e2178
      MAIL_FROM_ADDRESS: hello@innoscriptag.com
      MAIL_FROM_NAME: ${APP_NAME}
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ''
      AWS_USE_PATH_STYLE_ENDPOINT: 'false'
      VITE_APP_NAME: ${APP_NAME}
      NEWS_API_KEY: 31885c63bb46444d916ef6cdccb5ffb5
      GUARDIAN_API_KEY: 19890bef-daab-48e6-9be9-3664a8cad62e
      NY_TIME_API_KEY: lNeAiovtbMJqoV67144DR2URFEuhLxJD
      NY_TIME_SECRET: YuIdUVVzNtGKYy69
    depends_on:
      - app
    networks:
      - laravel

  # Queue Worker Service
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_queue
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Innoscripta
      APP_ENV: local
      APP_KEY: base64:WKaDO78IuJnT7SK7EV6W+njiqPNl3wfnwnvm1BOvAi8=
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      APP_MAINTENANCE_DRIVER: file
      PHP_CLI_SERVER_WORKERS: 4
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: Innoscripta
      DB_USERNAME: root
      DB_PASSWORD: root
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: 'false'
      SESSION_PATH: /
      SESSION_DOMAIN: null
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      MEMCACHED_HOST: 127.0.0.1
      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_MAILER: smtp
      MAIL_SCHEME: null
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: bcce57c4947bdb
      MAIL_PASSWORD: 3ca8b2ea1e2178
      MAIL_FROM_ADDRESS: hello@innoscriptag.com
      MAIL_FROM_NAME: ${APP_NAME}
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ''
      AWS_USE_PATH_STYLE_ENDPOINT: 'false'
      VITE_APP_NAME: ${APP_NAME}
      NEWS_API_KEY: 31885c63bb46444d916ef6cdccb5ffb5
      GUARDIAN_API_KEY: 19890bef-daab-48e6-9be9-3664a8cad62e
      NY_TIME_API_KEY: lNeAiovtbMJqoV67144DR2URFEuhLxJD
      NY_TIME_SECRET: YuIdUVVzNtGKYy69
    depends_on:
      - app
    networks:
      - laravel

# Networks
networks:
  laravel:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
